name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install root dependencies
        run: npm i

      - name: Install app dependencies
        run: npm i --prefix app

      - name: Install server dependencies
        run: npm i --prefix server

      - name: Install admin dependencies
        run: npm i --prefix admin

      - name: Install web dependencies
        run: npm i --prefix web

      - name: Run app tests
        run: npm run test:app

      - name: Run server tests
        run: npm run test:server

      - name: Run admin tests
        run: npm --prefix admin run test

      - name: Run app typecheck
        run: npm run test:app:typecheck

      - name: Run script tests
        run: npm run test:scripts

      - name: Build admin
        run: npm --prefix admin run build

      - name: Build web
        run: npm --prefix web run build
